config/routes.rb
Azot::Application.routes.draw do
   devise_for :users
   mount Usermanage::Engine => "/usermanage"
  
  get "/stat/destroy_all"  =>"stat#destroy_all"
  get "/stat" => "stat#index"

  get "main/index"

  get '/userapi/getrandomforvk/:id' => 'userapi#getrandomforvk', :id => :id 
  get '/userapi/getrandomfortwitter/:id' => 'userapi#getrandomfortwitter', :id => :id 
  get '/userapi/getrandomforfkuban/:type_id/:region_id' => 'userapi#getrandomforfkuban', :type_id => :type_id, :region_id=> :region_id 
  match '/userapi/dealclick/:id'=> 'userapi#dealclick', :id => :id
  #match '/userapi/visit/:id'=> 'userapi#visit', :id => :id
  
  resources :partners

  resources :regions

  post "deals/index"
  get "deals/destroy_all"
  resources :deals

  resources :categories

  resources :types

  mount Ckeditor::Engine => '/ckeditor'

  match '/detail/:id'=> 'main#detail', :id => :id 
  match '/:category'=> 'main#category', :category => :category
  match '/:category/:subcategory'=> 'main#subcategory', :category => :category, :subcategory => :subcategory
  #  match '/:category/:id'=> 'main#detail', :category => :category, :id => :id
  match '/:category/:subcategory/:id'=> 'main#detail', :category => :category, :subcategory => :subcategory, :id=>:id
 # match '/catalog/:category/:subcategory'=> 'main#subcategory', :category => :category, :subcategory => :subcategory

   root :to => 'main#index'

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :active, :category_id, :click, :costs, :isdelete, :description, :imgurl, :partner_id, :region_id, :shortdescription, :shorturl, :smallimgurl, :start_action, :stop_action, :title, :top, :type_id, :url, :user_id, :visit, :vkpost, :fkubankpost
  belongs_to :type
  belongs_to :category
  belongs_to :partner
  belongs_to :region
  belongs_to :user
  belongs_to :stat
  has_many :stat

  def self.on_top
  		Deal.where("deals.top=1 AND deals.active=1 AND deals.isdelete=0")
  end

  def self.notdelete
  		Deal.where(:isdelete=>0)
  end

 def self.active_from_category(category_id)
  		Deal.where(:category_id=>category_id, :active=>1,:isdelete=>0)
 end

 def self.notdelete_from_category(category_id)
  		Deal.where(:category_id=>category_id,:isdelete=>0)
 end

 def self.destroy_all
      Deal.update_all("isdelete=1")
 end

 def self.all_active_not_vk_post(type_id)
      Deal.where(:type_id=>type_id ,:active=>1,:isdelete=>0, :vkpost=>0)
 end

  def self.all_active_not_twitter_post(type_id)
      Deal.where(:type_id=>type_id ,:active=>1,:isdelete=>0, :twitterpost=>0)
  end

  def self.all_active_not_fkuban_post(type_id, region_id)
    Deal.where(:type_id=>type_id, :region_id=>region_id ,:active=>1,:isdelete=>0, :fkubankpost=>0)
  end

end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  load_and_authorize_resource 
  # GET /deals
  # GET /deals.json
  layout "admin"
  def index
    @cf= Categoryfilter.new

    if request.post?
      category_id= params[:categoryfilter][:category_id]
      session[:category_id] = category_id
      if category_id==""  #Сбрасываем фильтр категорий
       session[:category_id]= nil
      end
    end
    
    if session[:category_id]
      category_id= session[:category_id]
      @cf.category_id=category_id   #хочу в индию

      @deals = Deal.notdelete_from_category(category_id)
    else
      @deals = Deal.notdelete
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deals }
    end
end

  # GET /deals/1
  # GET /deals/1.json
  def show
    @deal = Deal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/new
  # GET /deals/new.json
  def new
    @deal = Deal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render json: @deal, status: :created, location: @deal }
      else
        format.html { render action: "new" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /deals/1
  # PUT /deals/1.json
  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end
  def destroy_all
    Deal.destroy_all()
    redirect_to deals_url 
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<%#= javascript_include_tag "ckeditor/init" %>
<%= form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
 <div class="span1">Тип:</div>
  <div class="span3">

    <%= f.select(:type_id, Type.all.collect {|p| [ p.name, p.id ] }, options ={:prompt => "-Выбор типа"})%>
  </div>

  <div class="span1">Категория:</div>
  <div class="span3">
    <%#= f.number_field :category_id %>
    <%#= f.select(:category_id, Category.all.collect {|p| [ p.name, p.id ] })%>
    <%= f.select(:category_id, Category.all.collect {|p| [ p.path.map{|i| i.name.to_s}, p.name, p.id ] })%>
  </div>

  <div class="span1">Регион:</div>
  <div class="span3">
    <%#= f.number_field :region_id %>
    <%= f.select(:region_id, Region.all.collect { |p| [ p.name, p.id ] }, options ={:prompt => "-Выбор региона"})%>
  </div>
</div> <!--class="row" -->

<div class="row">
  <div class="span1">Партнер:</div>
  <div class="span3">
    <%#= f.number_field :partner_id %>
    <%= f.select(:partner_id, Partner.all.collect {|p| [ p.name, p.id ] }, {:include_blank => 'Нет-'}, options ={:prompt => "-Выбор Партнера"})%>
  </div>

  <div class="span1">Пользователь:</div>
  <div class="span3"><%= f.number_field :user_id, :disabled=>true%></div>
</div> <!--class="row" -->

<div class="row">
  <div class="span1">Активно:</div>
  <div class="span1"><%= f.check_box :active %></div>

  <div class="span1">Удалено:</div>
  <div class="span1"><%= f.check_box :isdelete %></div>

  <div class="span2">На главной:</div>
  <div class="span1"><%= f.check_box :top %></div>

  <div class="span1">Стоимость:</div>
  <div class="span2"><%= f.text_field :costs %></div>
</div> <!--class="row" -->
<hr>
<div class="row">
  <div class="span2">Заголовок</div>
  <div class="span3"><%= f.text_field :title, :id=>"title_field" %></div> 
</div> <!--class="row" -->
<div class="row">
  <div class="span2">Краткое описание</div>
  <div class="span3"><%= f.text_field :shortdescription, :size => 150, :id=>"shortdescription_field" %></div> 
</div> <!--class="row" -->
  
 
  <div class="row">
    <div class="span10">
    Описание<br />
    <%#= f.text_area :description %>
    <%= f.text_area :description, :size => "80x80", :id=>"text_field" %>
    </div>
  </div> <!--class="row" -->
<hr>
<div class="row">
  <div class="span1">Картинка</div>
  <div class="span3"><%= f.text_field :imgurl %></div> 

  <div class="span2">Маленькая картинка</div>
  <div class="span3"><%= f.text_field :smallimgurl %></div> 
</div> <!--class="row" -->

 <div class="row">
  <div class="span1">Ссылка</div>
  <div class="span3"><%= f.text_field :url %></div> 

  <div class="span2">Сокр. ссылка</div>
  <div class="span3"><%= f.text_field :shorturl %></div> 
</div> <!--class="row" -->

 <div class="row">
  <div class="span1">Посещений</div>
  <div class="span3"><%= f.number_field :visit , :disabled=>true %></div> 

  <div class="span2">Кликов</div>
  <div class="span3"><%= f.number_field :click, :disabled=>true %></div> 
</div> <!--class="row" -->
 

  <div class="field">
    <%= f.label :start_action %><br />
    <%= f.datetime_select :start_action %>
  </div>
  <div class="field">
    <%= f.label :stop_action %><br />
    <%= f.datetime_select :stop_action %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>
<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<h1>Товары</h1> 

<%#= form_tag(:controller => "deals", :action => "index") do %>
<%#= select(:form,:category_id,  Category.all.collect {|p| [ p.path.map{|i| i.name.to_s}, p.name, p.id ] }, {:include_blank => 'Категория-'})%>
<%#= select( :form,:region_id, Region.all.collect { |p| [p.name, p.id] }, {:include_blank => 'Город'}) %>
<%#= submit_tag("Выбрать") %>
<%# end %>

<%= form_for @cf, :url => { :action => "index" } do |f| %>
<%= f.select(:category_id,  Category.all.collect {|p| [ p.path.map{|i| i.name.to_s}, p.name, p.id ] }, {:include_blank => 'Категория-'})%>
  <%= f.submit "Выбрать" %>
<% end %>
<a href="/deals/destroy_all" class="btn btn-danger">Удалить все!</a>
<hr>


<%= link_to  new_deal_path, :class=>"btn btn-info" do %><i class="icon-gift"></i>Добавить товар<%end%> 
<table class="table table-striped">
  <tr>
    
    <th>Тип</th>
    <th>Категория</th>
    <th>Активно</th>
    <th>Удалено</th>
    <th>На главной</th>
    <th>Заголовок</th>
    <th>Стоимость</th>

   <!-- <th>Кликов</th>
    <th>Посещений</th> -->
    <th>Начало</th>
    <th>Окончание</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deals.each do |deal| %>
  <tr>
  
    <td><%= deal.type.try(:name) %></td>
    <td><%= deal.category.try(:name) %></td>
    <td><%if deal.active %> Активно <%else%>Неактивно <% end %></td>
    <td><%if deal.isdelete %> Да <%else%>Нет<% end %></td>
    <td><%if deal.top %> Да <%else%>Нет<% end %></td>
    <td><%= deal.title %></td>
    <td><%= deal.costs %></td>
   <!-- <td><%#= deal.click %></td>
    <td><%#= deal.visit %></td> -->
    <td><%= deal.start_action %></td>
    <td><%= deal.stop_action %></td>
    <td><%= link_to 'Show', deal %></td>
    <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
    <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New Deal', new_deal_path %>
<%= link_to  new_deal_path, :class=>"btn btn-info" do %><i class="icon-gift"></i>Добавить товар<%end%> 

app/views/deals/new.html.erb
<h1>New deal</h1>
<%= link_to 'Back', deals_path %>
<%= render 'form' %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>

<%= render "shared/show_deal" %>

  <div class="field">
    От<br />
    <%= @deal.start_action %>
  </div>
  <div class="field">
    До<br />
    <%= @deal.stop_action %>
  </div>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>